package practice.utils;

import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.SignatureAlgorithm;
import org.springframework.stereotype.Component;

import java.util.Date;

@Component
public class JwtTool {
    private static final String SECRET_KEY = "techjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoytechjoy";
    private static final long EXPIRATION_TIME = 86400_000;

    public static String generateToken(String subject) {
        return Jwts.builder()
                .setHeaderParam("typ", "JWT")
                .setSubject(subject)
                .setIssuedAt(new Date())
                .setExpiration(new Date(System.currentTimeMillis() + EXPIRATION_TIME))
                .signWith(SignatureAlgorithm.HS512, SECRET_KEY)
                .compact();
    }

    public static String getPayload(String token) {
        try {
            return Jwts.parser()
                    .setSigningKey(SECRET_KEY)
                    .build()
                    .parseClaimsJws(token)
                    .getBody()
                    .getSubject();
        } catch (Exception e) {
            return null;
        }
    }
}
