spring:
  application:
    name: area-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: techjoy
    url: jdbc:mysql://localhost:3306/practice?useSSL=false&serverTimezone=UTC

server:
  port: 8083
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

  global-config:
    db-config:
      id-type: none
